language: python
python:
  - 3.7
  - 3.8
env:
  - DJANGO="<2.2"
  - DJANGO="<3.0"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==3.7.1
  - pip install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
